services:
  web:
    build: .
    domain: ${DOMAIN}
    environment:
      - ALGOLIA_APP
      - ALGOLIA_INDEX
      - ALGOLIA_KEY_ADMIN
      - ALGOLIA_KEY_SEARCH
      - DEVELOPMENT=false
    health:
      path: /introduction/overview
      interval: 30
    port: https:3000
